# cutains information
measurement_error_pos: 0.0
measurement_error_vel: 0.1
delay: 0.0
use_kalman_filter: true
s_w: 2.0e+2
s_v: 1.0e-6
initial_pos_var: 0.003
initial_vel_var: 0.5

use_combined_model: true

# Names of joints in correct outputted order
joint_names: [
  "lShldr", "lForeArm", "lHand", "rShldr", 
  "rForeArm", "rHand", "neck", "hip", "head"
]
joint_v_max: [
  2, 2, 2, 2, 2, 2, 2, 2, 2
]

joint_a_max: [
  50, 50, 50, 50, 50, 50, 20, 20, 50
]
# All values are in the 95% Quantiles defined in DIN 33402-2
# There are no values about arm circumfence, so we take the leg values as overapproximation.
bodies:
  - name: "lUpperArm" 
    proximal: "lShldr"
    distal: "lForeArm"
    thickness: 0.2
    max_contact_energy:
      unconstrained: 
        link: 1.5  # We assume blunt contacts for robot links
        blunt: 1.5 # From ISO/TS 15066:2016
        wedge: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.2  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 1.5  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "lLowerArm"
    proximal: "lForeArm"
    distal: "lHand"
    thickness: 0.132
    max_contact_energy:
      unconstrained: 
        link: 1.3  # We assume blunt contacts for robot links
        blunt: 1.3  # From ISO/TS 15066:2016
        wedge: 2.0  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.375  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.9  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 1.3  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "lHand"
    proximal: "lHand"
    distal: "lHand"
    thickness: 0.206
    max_contact_energy:
      unconstrained: 
        link: 0.49  # We assume blunt contacts for robot links
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 2.0  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.375  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.9  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "rUpperArm" 
    proximal: "rShldr"
    distal: "rForeArm"
    thickness: 0.2
    max_contact_energy:
      unconstrained: 
        link: 1.5  # We assume blunt contacts for robot links
        blunt: 1.5 # From ISO/TS 15066:2016
        wedge: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.2  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 1.5  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "rLowerArm"
    proximal: "rForeArm"
    distal: "rHand"
    thickness: 0.132
    max_contact_energy:
      unconstrained: 
        link: 1.3  # We assume blunt contacts for robot links
        blunt: 1.3  # From ISO/TS 15066:2016
        wedge: 2.0  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.375  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.9  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 1.3  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "rHand"
    proximal: "rHand"
    distal: "rHand"
    thickness: 0.206
    max_contact_energy:
      unconstrained: 
        link: 0.49  # We assume blunt contacts for robot links
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 2.0  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.375  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.9  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "torso"
    proximal: "hip"
    distal: "neck"
    thickness: 0.434
    max_contact_energy:
      unconstrained: 
        link: 1.6  # We assume blunt contacts for robot links
        blunt: 1.6 # From ISO/TS 15066:2016
        wedge: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.2  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 1.6  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
  
  - name: "head"
    proximal: "head"
    distal: "head"
    thickness: 0.434
    max_contact_energy:  # For the head, we take the minimum of ISO/TS 15066:2016 and Kirschner 2024
      unconstrained: 
        link: 0.11  # We assume blunt contacts for robot links
        blunt: 0.11  # From ISO/TS 15066:2016
        wedge: 0.11  # From ISO/TS 15066:2016
        edge: 0.11  # From ISO/TS 15066:2016
        sheet: 0.11  # From ISO/TS 15066:2016
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 0.11  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

extremities:
  - name: "lArm"
    base: "lShldr"
    end: "lHand"
    length: 1.0 # See Tabelle 21 — Reichweite nach vorn (Griffachse) - Half a hand length.
    thickness: 0.0
        max_contact_energy:
      unconstrained: 
        link: 0.49  # We assume blunt contacts for robot links
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.2  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11 # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
    
  - name: "rArm"
    base: "rShldr"
    end: "rHand"
    length: 1.0 # See Tabelle 21 — Reichweite nach vorn (Griffachse) - Half a hand length.
    thickness: 0.0
        max_contact_energy:
      unconstrained: 
        link: 0.49  # We assume blunt contacts for robot links
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.2  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11 # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

# 0: L_UpperArm
# 1: L_LowerArm
# 2: L_Hand
# 3: R_UpperArm
# 4: R_LowerArm
# 5: R_Hand
# 6: Torso
# 7: Head
unclampable_body_parts: [
  ["lUpperArm", "lLowerArm"],
  ["lUpperArm", "lHand"],
  ["lUpperArm", "rUpperArm"],
  ["lUpperArm", "torso"],
  ["lUpperArm", "head"],
  ["lLowerArm", "lHand"],
  ["lLowerArm", "rUpperArm"],
  ["lLowerArm", "torso"],
  ["lLowerArm", "head"],
  ["lHand", "rUpperArm"],
  ["lHand", "torso"],
  ["lHand", "head"],
  ["rUpperArm", "rLowerArm"],
  ["rUpperArm", "rHand"],
  ["rUpperArm", "torso"],
  ["rUpperArm", "head"],
  ["rLowerArm", "rHand"],
  ["rLowerArm", "torso"],
  ["rLowerArm", "head"],
  ["rHand", "torso"],
  ["rHand", "head"],
  ["torso", "head"]
]
