# cutains information
measurement_error_pos: 0.1
measurement_error_vel: 1.0
delay: 0.01
use_kalman_filter: true
s_w: 2.0e+2
s_v: 1.0e-6
initial_pos_var: 0.003
initial_vel_var: 0.5

use_combined_model: true

# Names of joints in correct outputted order
joint_names: [
  "rightShoulder", "rightElbow", "rightWrist"
]
joint_v_max: [
  2, 2, 2
]

joint_a_max: [
  50, 50, 50
]

bodies:
  - name: "rightUpperArm" 
    proximal: "rightShoulder"
    distal: "rightElbow"
    thickness: 0.1
    max_contact_energy:
      unconstrained: 
        link: 1.5  # We assume blunt contacts for robot links
        blunt: 1.5 # From ISO/TS 15066:2016
        wedge: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.2  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.0  # We don't want to allow clamping for robot links.
        blunt: 0.375  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "rightLowerArm"
    proximal: "rightElbow"
    distal: "rightWrist"
    thickness: 0.1
    max_contact_energy:
      unconstrained: 
        link: 1.3  # We assume blunt contacts for robot links
        blunt: 1.3  # From ISO/TS 15066:2016
        wedge: 2.0  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.375  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.9  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.0  # We don't want to allow clamping for robot links.
        blunt: 0.325  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "rightHand"
    proximal: "rightWrist"
    distal: "rightWrist"
    thickness: 0.208
    max_contact_energy:
      unconstrained: 
        link: 0.49  # We assume blunt contacts for robot links
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 2.0  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.375  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.9  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.0  # We don't want to allow clamping for robot links.
        blunt: 0.12  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

extremities:
  - name: "rightArm"
    base: "rightShoulder"
    end: "rightWrist"
    length: 0.725
    thickness: 0.0
    max_contact_energy:  # For the head, we take the minimum of ISO/TS 15066:2016 and Kirschner 2024
      unconstrained: 
        link: 0.11  # We assume blunt contacts for robot links
        blunt: 0.11  # From ISO/TS 15066:2016
        wedge: 0.11  # From ISO/TS 15066:2016
        edge: 0.11  # From ISO/TS 15066:2016
        sheet: 0.11  # From ISO/TS 15066:2016
      constrained:
        link: 0.0  # We don't want to allow clamping for robot links.
        blunt: 0.0275  # From ISO/TS 15066:2016
        wedge: 0.0275  # From ISO/TS 15066:2016
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.0275  # From ISO/TS 15066:2016

unclampable_body_parts: [
  ["rightUpperArm", "rightLowerArm"],
  ["rightUpperArm", "rightHand"],
  ["rightLowerArm", "rightHand"]
]