# cutains information
measurement_error_pos: 0.2
measurement_error_vel: 0.1
delay: 0.01
use_kalman_filter: false
s_w: 2.0e+2
s_v: 1.0e-6
initial_pos_var: 0.003
initial_vel_var: 0.5

use_combined_model: true

# Names of joints in correct outputted order
joint_names: [
  "head"
]
joint_v_max: [
  1
]

joint_a_max: [
  10
]

bodies:
  - name: "head" 
    proximal: "head"
    distal: "head"
    thickness: 0.1
    max_contact_energy:  # For the head, we take the minimum of ISO/TS 15066:2016 and Kirschner 2024
      unconstrained: 
        link: 0.11  # We assume blunt contacts for robot links
        blunt: 0.11  # From ISO/TS 15066:2016
        wedge: 0.11  # From ISO/TS 15066:2016
        edge: 0.11  # From ISO/TS 15066:2016
        sheet: 0.11  # From ISO/TS 15066:2016
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 0.11  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

extremities: