# cutains information
measurement_error_pos: 0.0
measurement_error_vel: 0.1
delay: 0.0
use_kalman_filter: true
s_w: 2.0e+2
s_v: 1.0e-6
initial_pos_var: 0.003
initial_vel_var: 0.5

use_combined_model: true

# Names of joints in correct outputted order
joint_names: [
  "L_Hip", "R_Hip", "Torso", "L_Knee", "R_Knee",
  "Spine", "L_Ankle", "R_Ankle", "Chest", "L_Toe",
  "R_Toe", "Neck", "L_Thorax", "R_Thorax", "Head",
  "L_Shoulder", "R_Shoulder", "L_Elbow", "R_Elbow", "L_Wrist",
  "R_Wrist", "L_Hand", "R_Hand"
]

joint_v_max: [
  2, 2, 2, 2, 2, 
  2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 
  2, 2, 2, 2, 2,
  2, 2, 2
]

joint_a_max: [
  20, 20, 20, 30, 30,
  25, 30, 30, 20, 30,
  30, 25, 25, 25, 25,
  50, 50, 50, 50, 50,
  50, 50, 50
]

bodies:
  - name: "L_UpperArm" 
    proximal: "L_Shoulder"
    distal: "L_Elbow"
    thickness: 0.2 # 95 percentile of upper leg diameter according to DIN 33402-2:2020-12 (There is no information on upper arm diameter.)
    max_contact_energy:
      unconstrained: 
        link: 1.5  # We assume blunt contacts for robot links
        blunt: 1.5 # From ISO/TS 15066:2016
        wedge: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.2  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 1.5  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "L_LowerArm"
    proximal: "L_Elbow"
    distal: "L_Wrist"
    thickness: 0.132 # 95 percentile of lower leg diameter according to DIN 33402-2:2020-12 (There is no information on lower arm diameter.)
    max_contact_energy:
      unconstrained: 
        link: 1.3  # We assume blunt contacts for robot links
        blunt: 1.3  # From ISO/TS 15066:2016
        wedge: 2.0  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.375  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.9  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 1.3  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "L_Hand"
    proximal: "L_Wrist"
    distal: "L_Hand"
    thickness: 0.206 # 95 percentile of hand length according to DIN 33402-2:2020-12
    max_contact_energy:
      unconstrained: 
        link: 0.49  # We assume blunt contacts for robot links
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 2.0  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.375  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.9  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "R_UpperArm" 
    proximal: "R_Shoulder"
    distal: "R_Elbow"
    thickness: 0.2 # 95 percentile of upper leg diameter according to DIN 33402-2:2020-12 (There is no information on upper arm diameter.)
    max_contact_energy:
      unconstrained: 
        link: 1.5  # We assume blunt contacts for robot links
        blunt: 1.5 # From ISO/TS 15066:2016
        wedge: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.2  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 1.5  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "R_LowerArm"
    proximal: "R_Elbow"
    distal: "R_Wrist"
    thickness: 0.132 # 95 percentile of lower leg diameter according to DIN 33402-2:2020-12 (There is no information on lower arm diameter.)
    max_contact_energy:
      unconstrained: 
        link: 1.3  # We assume blunt contacts for robot links
        blunt: 1.3  # From ISO/TS 15066:2016
        wedge: 2.0  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.375  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.9  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 1.3  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "R_Hand"
    proximal: "R_Wrist"
    distal: "R_Hand"
    thickness: 0.206 # 95 percentile of hand length according to DIN 33402-2:2020-12
    max_contact_energy:
      unconstrained: 
        link: 0.49  # We assume blunt contacts for robot links
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 2.0  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.375  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.9  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

  - name: "Torso"
    proximal: "Torso"
    distal: "Neck"
    thickness: 0.434 # Lays in 95% of Shoulder width according to DIN 33402-2:2020-12
    max_contact_energy:
      unconstrained: 
        link: 1.6  # We assume blunt contacts for robot links
        blunt: 1.6 # From ISO/TS 15066:2016
        wedge: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.2  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 1.6  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
  
  - name: "Head"
    proximal: "Neck"
    distal: "Head"
    thickness: 0.434 # Lays in 95% of Shoulder width according to DIN 33402-2:2020-12
    max_contact_energy:  # For the head, we take the minimum of ISO/TS 15066:2016 and Kirschner 2024
      unconstrained: 
        link: 0.11  # We assume blunt contacts for robot links
        blunt: 0.11  # From ISO/TS 15066:2016
        wedge: 0.11  # From ISO/TS 15066:2016
        edge: 0.11  # From ISO/TS 15066:2016
        sheet: 0.11  # From ISO/TS 15066:2016
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 0.11  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

extremities:
  - name: "L_Arm"
    base: "L_Shoulder"
    end: "L_Hand"
    length: 0.825 # 95 percentile of reach to the front according to DIN 33402-2:2020-12
    thickness: 0.0
        max_contact_energy:
      unconstrained: 
        link: 0.49  # We assume blunt contacts for robot links
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.2  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11 # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
    
  - name: "R_Arm"
    base: "R_Shoulder"
    end: "R_Hand"
    length: 0.825 # 95 percentile of reach to the front according to DIN 33402-2:2020-12
    thickness: 0.0
        max_contact_energy:
      unconstrained: 
        link: 0.49  # We assume blunt contacts for robot links
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        edge: 0.2  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
        sheet: 0.5  # From Kirschner 2024: Towards Unconstrained Collision Injury Protection Data Sets: Initial Surrogate Experiments for the Human Hand
      constrained:
        link: 0.01  # We only allow a very low impact energy for links as clamping is generally undesirable here.
        blunt: 0.49  # From ISO/TS 15066:2016
        wedge: 0.05  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        edge: 0.02  # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database
        sheet: 0.11 # From Kirschner 2024: Towards Safe Robot Use with Edged or Pointed Objects: A Surrogate Study Assembling a Human Hand Injury Protection Database

# 0: L_UpperArm
# 1: L_LowerArm
# 2: L_Hand
# 3: R_UpperArm
# 4: R_LowerArm
# 5: R_Hand
# 6: Torso
# 7: Head
unclampable_body_parts: [
  ["L_UpperArm", "L_LowerArm"],
  ["L_UpperArm", "L_Hand"],
  ["L_UpperArm", "R_UpperArm"],
  ["L_UpperArm", "Torso"],
  ["L_UpperArm", "Head"],
  ["L_LowerArm", "L_Hand"],
  ["L_LowerArm", "R_UpperArm"],
  ["L_LowerArm", "Torso"],
  ["L_LowerArm", "Head"],
  ["L_Hand", "R_UpperArm"],
  ["L_Hand", "Torso"],
  ["L_Hand", "Head"],
  ["R_UpperArm", "R_LowerArm"],
  ["R_UpperArm", "R_Hand"],
  ["R_UpperArm", "Torso"],
  ["R_UpperArm", "Head"],
  ["R_LowerArm", "R_Hand"],
  ["R_LowerArm", "Torso"],
  ["R_LowerArm", "Head"],
  ["R_Hand", "Torso"],
  ["R_Hand", "Head"],
  ["Torso", "Head"]
]
