robot_name: siciliano

nb_joints: 2

secure_radius: 0

transformation_matrices: [
  1, 0, 0, 0,
  0, 1, 0, 0,
  0, 0, 1, 0,
  0, 0, 0, 1,
  1, 0, 0, 1,
  0, 1, 0, 0,
  0, 0, 1, 0,
  0, 0, 0, 1
]

enclosures: [
  0, 0, 0,
  1, 0, 0,
  1,
  0, 0, 0,
  2, 0, 0,
  1
]

# In kg
link_masses: [
  3.0,
  2.0
]

# ixx, ixy, ixz, iyy, iyz, izz
link_inertias: [
  0.0, 0, 0, 0.0, 0, 0.03,
  0.0, 0, 0, 0.0, 0, 0.02
]

# rpy, xyz
link_centers_of_mass: [
  0.5, 0, 0, 0, 0, 0,
  1.0, 0, 0, 0, 0, 0
]